// <auto-generated />
using System;
using MVC_Solutions_In_Retail.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Solutions_In_Retail.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20230411194823_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MVC_Solutions_In_Retail.Model.MyCatalogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MyProductsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MyProductsId");

                    b.ToTable("MyCatalogue");
                });

            modelBuilder.Entity("MVC_Solutions_In_Retail.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MVC_Solutions_In_Retail.Model.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("MVC_Solutions_In_Retail.Model.MyCatalogue", b =>
                {
                    b.HasOne("MVC_Solutions_In_Retail.Model.Product", "MyProducts")
                        .WithMany()
                        .HasForeignKey("MyProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyProducts");
                });

            modelBuilder.Entity("MVC_Solutions_In_Retail.Model.Product", b =>
                {
                    b.HasOne("MVC_Solutions_In_Retail.Model.Supplier", null)
                        .WithMany("Products")
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("MVC_Solutions_In_Retail.Model.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
